In [34]:
import pandas as pd
import numpy as np
import tensorflow as tf
# Read the csv file
df = pd.read_csv('data.csv', header=None)

# Remove empty rows
df = df.replace(np.nan,0)

# Convert the dataframe to a numpy array
data = df.to_numpy()

In [2]:
data

array([[0.0, 'R', 'P', ..., 'R', 'R', 'R']], dtype=object)

In [3]:
data.shape

(1, 200000)

In [4]:
Mapping = {'R':1,'P':2,'S':3}

def map_values(x):
    return Mapping.get(x, x)

In [5]:
vectorized_map_values = np.vectorize(map_values)
converted_data = vectorized_map_values(data)

In [10]:
converted_data.dtype

array([[0., 1., 2., ..., 1., 1., 1.]])

In [31]:
segments = []

for i in range(0, converted_data.shape[1] - 20):
    segment = converted_data[0][i:i+20]
    segments.append(segment)


In [32]:
segments

[array([0., 1., 2., 2., 3., 1., 1., 2., 2., 3., 1., 1., 2., 2., 3., 1., 1.,
        2., 2., 3.]),
 array([1., 2., 2., 3., 1., 1., 2., 2., 3., 1., 1., 2., 2., 3., 1., 1., 2.,
        2., 3., 1.]),
 array([2., 2., 3., 1., 1., 2., 2., 3., 1., 1., 2., 2., 3., 1., 1., 2., 2.,
        3., 1., 1.]),
 array([2., 3., 1., 1., 2., 2., 3., 1., 1., 2., 2., 3., 1., 1., 2., 2., 3.,
        1., 1., 2.]),
 array([3., 1., 1., 2., 2., 3., 1., 1., 2., 2., 3., 1., 1., 2., 2., 3., 1.,
        1., 2., 2.]),
 array([1., 1., 2., 2., 3., 1., 1., 2., 2., 3., 1., 1., 2., 2., 3., 1., 1.,
        2., 2., 3.]),
 array([1., 2., 2., 3., 1., 1., 2., 2., 3., 1., 1., 2., 2., 3., 1., 1., 2.,
        2., 3., 1.]),
 array([2., 2., 3., 1., 1., 2., 2., 3., 1., 1., 2., 2., 3., 1., 1., 2., 2.,
        3., 1., 1.]),
 array([2., 3., 1., 1., 2., 2., 3., 1., 1., 2., 2., 3., 1., 1., 2., 2., 3.,
        1., 1., 2.]),
 array([3., 1., 1., 2., 2., 3., 1., 1., 2., 2., 3., 1., 1., 2., 2., 3., 1.,
        1., 2., 2.]),
 array([1., 1., 2., 

In [35]:
dataset = tf.data.Dataset.from_tensor_slices(converted_data)

In [36]:
dataset

<TensorSliceDataset element_spec=TensorSpec(shape=(200000,), dtype=tf.float64, name=None)>

In [ ]:
BATCH_SIZE = 20
batched_data= dataset.batch(BATCH_SIZE, drop_remainder=True)

In [ ]:
batched_da